//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34003
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace SearchShot.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="info", Namespace="http://schemas.datacontract.org/2004/07/WS")]
    public partial class info : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loginField;
        
        private string nomField;
        
        private string prenomField;
        
        private string villeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nom {
            get {
                return this.nomField;
            }
            set {
                if ((object.ReferenceEquals(this.nomField, value) != true)) {
                    this.nomField = value;
                    this.RaisePropertyChanged("nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string prenom {
            get {
                return this.prenomField;
            }
            set {
                if ((object.ReferenceEquals(this.prenomField, value) != true)) {
                    this.prenomField = value;
                    this.RaisePropertyChanged("prenom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ville {
            get {
                return this.villeField;
            }
            set {
                if ((object.ReferenceEquals(this.villeField, value) != true)) {
                    this.villeField = value;
                    this.RaisePropertyChanged("ville");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="personnes", Namespace="http://schemas.datacontract.org/2004/07/WS")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SearchShot.ServiceReference1.info))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Collections.Generic.List<string>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<string>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Collections.Generic.List<int>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<int>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<System.Collections.Generic.List<object>>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
    public partial class personnes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.List<System.Collections.Generic.List<string>> date_inscField;
        
        private System.Collections.Generic.List<System.Collections.Generic.List<int>> idField;
        
        private System.Collections.Generic.List<System.Collections.Generic.List<object>> imgField;
        
        private System.Collections.Generic.List<System.Collections.Generic.List<string>> loginField;
        
        private System.Collections.Generic.List<System.Collections.Generic.List<int>> scoreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.List<string>> date_insc {
            get {
                return this.date_inscField;
            }
            set {
                if ((object.ReferenceEquals(this.date_inscField, value) != true)) {
                    this.date_inscField = value;
                    this.RaisePropertyChanged("date_insc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.List<int>> id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.List<object>> img {
            get {
                return this.imgField;
            }
            set {
                if ((object.ReferenceEquals(this.imgField, value) != true)) {
                    this.imgField = value;
                    this.RaisePropertyChanged("img");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.List<string>> login {
            get {
                return this.loginField;
            }
            set {
                if ((object.ReferenceEquals(this.loginField, value) != true)) {
                    this.loginField = value;
                    this.RaisePropertyChanged("login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<System.Collections.Generic.List<int>> score {
            get {
                return this.scoreField;
            }
            set {
                if ((object.ReferenceEquals(this.scoreField, value) != true)) {
                    this.scoreField = value;
                    this.RaisePropertyChanged("score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.IAsyncResult BeginGetData(string value, System.AsyncCallback callback, object asyncState);
        
        string EndGetData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Inscription", ReplyAction="http://tempuri.org/IService1/InscriptionResponse")]
        System.IAsyncResult BeginInscription(string password, string login, string mail, System.AsyncCallback callback, object asyncState);
        
        int EndInscription(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/Authentification", ReplyAction="http://tempuri.org/IService1/AuthentificationResponse")]
        System.IAsyncResult BeginAuthentification(string login, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndAuthentification(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/SetInfos", ReplyAction="http://tempuri.org/IService1/SetInfosResponse")]
        System.IAsyncResult BeginSetInfos(string nom, string prenom, string login, string ville, int id, System.AsyncCallback callback, object asyncState);
        
        string EndSetInfos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetInfos", ReplyAction="http://tempuri.org/IService1/GetInfosResponse")]
        System.IAsyncResult BeginGetInfos(int id_joueur, System.AsyncCallback callback, object asyncState);
        
        SearchShot.ServiceReference1.info EndGetInfos(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IService1/GetPeopleInfos", ReplyAction="http://tempuri.org/IService1/GetPeopleInfosResponse")]
        System.IAsyncResult BeginGetPeopleInfos(System.AsyncCallback callback, object asyncState);
        
        SearchShot.ServiceReference1.personnes EndGetPeopleInfos(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SearchShot.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthentificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthentificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SetInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SetInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SearchShot.ServiceReference1.info Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SearchShot.ServiceReference1.info)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetPeopleInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPeopleInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SearchShot.ServiceReference1.personnes Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SearchShot.ServiceReference1.personnes)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SearchShot.ServiceReference1.IService1>, SearchShot.ServiceReference1.IService1 {
        
        private BeginOperationDelegate onBeginGetDataDelegate;
        
        private EndOperationDelegate onEndGetDataDelegate;
        
        private System.Threading.SendOrPostCallback onGetDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginInscriptionDelegate;
        
        private EndOperationDelegate onEndInscriptionDelegate;
        
        private System.Threading.SendOrPostCallback onInscriptionCompletedDelegate;
        
        private BeginOperationDelegate onBeginAuthentificationDelegate;
        
        private EndOperationDelegate onEndAuthentificationDelegate;
        
        private System.Threading.SendOrPostCallback onAuthentificationCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetInfosDelegate;
        
        private EndOperationDelegate onEndSetInfosDelegate;
        
        private System.Threading.SendOrPostCallback onSetInfosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetInfosDelegate;
        
        private EndOperationDelegate onEndGetInfosDelegate;
        
        private System.Threading.SendOrPostCallback onGetInfosCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetPeopleInfosDelegate;
        
        private EndOperationDelegate onEndGetPeopleInfosDelegate;
        
        private System.Threading.SendOrPostCallback onGetPeopleInfosCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetDataCompletedEventArgs> GetDataCompleted;
        
        public event System.EventHandler<InscriptionCompletedEventArgs> InscriptionCompleted;
        
        public event System.EventHandler<AuthentificationCompletedEventArgs> AuthentificationCompleted;
        
        public event System.EventHandler<SetInfosCompletedEventArgs> SetInfosCompleted;
        
        public event System.EventHandler<GetInfosCompletedEventArgs> GetInfosCompleted;
        
        public event System.EventHandler<GetPeopleInfosCompletedEventArgs> GetPeopleInfosCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SearchShot.ServiceReference1.IService1.BeginGetData(string value, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetData(value, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SearchShot.ServiceReference1.IService1.EndGetData(System.IAsyncResult result) {
            return base.Channel.EndGetData(result);
        }
        
        private System.IAsyncResult OnBeginGetData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string value = ((string)(inValues[0]));
            return ((SearchShot.ServiceReference1.IService1)(this)).BeginGetData(value, callback, asyncState);
        }
        
        private object[] OnEndGetData(System.IAsyncResult result) {
            string retVal = ((SearchShot.ServiceReference1.IService1)(this)).EndGetData(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDataCompleted(object state) {
            if ((this.GetDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDataAsync(string value) {
            this.GetDataAsync(value, null);
        }
        
        public void GetDataAsync(string value, object userState) {
            if ((this.onBeginGetDataDelegate == null)) {
                this.onBeginGetDataDelegate = new BeginOperationDelegate(this.OnBeginGetData);
            }
            if ((this.onEndGetDataDelegate == null)) {
                this.onEndGetDataDelegate = new EndOperationDelegate(this.OnEndGetData);
            }
            if ((this.onGetDataCompletedDelegate == null)) {
                this.onGetDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDataCompleted);
            }
            base.InvokeAsync(this.onBeginGetDataDelegate, new object[] {
                        value}, this.onEndGetDataDelegate, this.onGetDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SearchShot.ServiceReference1.IService1.BeginInscription(string password, string login, string mail, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInscription(password, login, mail, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int SearchShot.ServiceReference1.IService1.EndInscription(System.IAsyncResult result) {
            return base.Channel.EndInscription(result);
        }
        
        private System.IAsyncResult OnBeginInscription(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string password = ((string)(inValues[0]));
            string login = ((string)(inValues[1]));
            string mail = ((string)(inValues[2]));
            return ((SearchShot.ServiceReference1.IService1)(this)).BeginInscription(password, login, mail, callback, asyncState);
        }
        
        private object[] OnEndInscription(System.IAsyncResult result) {
            int retVal = ((SearchShot.ServiceReference1.IService1)(this)).EndInscription(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInscriptionCompleted(object state) {
            if ((this.InscriptionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InscriptionCompleted(this, new InscriptionCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InscriptionAsync(string password, string login, string mail) {
            this.InscriptionAsync(password, login, mail, null);
        }
        
        public void InscriptionAsync(string password, string login, string mail, object userState) {
            if ((this.onBeginInscriptionDelegate == null)) {
                this.onBeginInscriptionDelegate = new BeginOperationDelegate(this.OnBeginInscription);
            }
            if ((this.onEndInscriptionDelegate == null)) {
                this.onEndInscriptionDelegate = new EndOperationDelegate(this.OnEndInscription);
            }
            if ((this.onInscriptionCompletedDelegate == null)) {
                this.onInscriptionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInscriptionCompleted);
            }
            base.InvokeAsync(this.onBeginInscriptionDelegate, new object[] {
                        password,
                        login,
                        mail}, this.onEndInscriptionDelegate, this.onInscriptionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SearchShot.ServiceReference1.IService1.BeginAuthentification(string login, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthentification(login, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool SearchShot.ServiceReference1.IService1.EndAuthentification(System.IAsyncResult result) {
            return base.Channel.EndAuthentification(result);
        }
        
        private System.IAsyncResult OnBeginAuthentification(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string login = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((SearchShot.ServiceReference1.IService1)(this)).BeginAuthentification(login, password, callback, asyncState);
        }
        
        private object[] OnEndAuthentification(System.IAsyncResult result) {
            bool retVal = ((SearchShot.ServiceReference1.IService1)(this)).EndAuthentification(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthentificationCompleted(object state) {
            if ((this.AuthentificationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthentificationCompleted(this, new AuthentificationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthentificationAsync(string login, string password) {
            this.AuthentificationAsync(login, password, null);
        }
        
        public void AuthentificationAsync(string login, string password, object userState) {
            if ((this.onBeginAuthentificationDelegate == null)) {
                this.onBeginAuthentificationDelegate = new BeginOperationDelegate(this.OnBeginAuthentification);
            }
            if ((this.onEndAuthentificationDelegate == null)) {
                this.onEndAuthentificationDelegate = new EndOperationDelegate(this.OnEndAuthentification);
            }
            if ((this.onAuthentificationCompletedDelegate == null)) {
                this.onAuthentificationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthentificationCompleted);
            }
            base.InvokeAsync(this.onBeginAuthentificationDelegate, new object[] {
                        login,
                        password}, this.onEndAuthentificationDelegate, this.onAuthentificationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SearchShot.ServiceReference1.IService1.BeginSetInfos(string nom, string prenom, string login, string ville, int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetInfos(nom, prenom, login, ville, id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        string SearchShot.ServiceReference1.IService1.EndSetInfos(System.IAsyncResult result) {
            return base.Channel.EndSetInfos(result);
        }
        
        private System.IAsyncResult OnBeginSetInfos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string nom = ((string)(inValues[0]));
            string prenom = ((string)(inValues[1]));
            string login = ((string)(inValues[2]));
            string ville = ((string)(inValues[3]));
            int id = ((int)(inValues[4]));
            return ((SearchShot.ServiceReference1.IService1)(this)).BeginSetInfos(nom, prenom, login, ville, id, callback, asyncState);
        }
        
        private object[] OnEndSetInfos(System.IAsyncResult result) {
            string retVal = ((SearchShot.ServiceReference1.IService1)(this)).EndSetInfos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSetInfosCompleted(object state) {
            if ((this.SetInfosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetInfosCompleted(this, new SetInfosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetInfosAsync(string nom, string prenom, string login, string ville, int id) {
            this.SetInfosAsync(nom, prenom, login, ville, id, null);
        }
        
        public void SetInfosAsync(string nom, string prenom, string login, string ville, int id, object userState) {
            if ((this.onBeginSetInfosDelegate == null)) {
                this.onBeginSetInfosDelegate = new BeginOperationDelegate(this.OnBeginSetInfos);
            }
            if ((this.onEndSetInfosDelegate == null)) {
                this.onEndSetInfosDelegate = new EndOperationDelegate(this.OnEndSetInfos);
            }
            if ((this.onSetInfosCompletedDelegate == null)) {
                this.onSetInfosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetInfosCompleted);
            }
            base.InvokeAsync(this.onBeginSetInfosDelegate, new object[] {
                        nom,
                        prenom,
                        login,
                        ville,
                        id}, this.onEndSetInfosDelegate, this.onSetInfosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SearchShot.ServiceReference1.IService1.BeginGetInfos(int id_joueur, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInfos(id_joueur, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchShot.ServiceReference1.info SearchShot.ServiceReference1.IService1.EndGetInfos(System.IAsyncResult result) {
            return base.Channel.EndGetInfos(result);
        }
        
        private System.IAsyncResult OnBeginGetInfos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id_joueur = ((int)(inValues[0]));
            return ((SearchShot.ServiceReference1.IService1)(this)).BeginGetInfos(id_joueur, callback, asyncState);
        }
        
        private object[] OnEndGetInfos(System.IAsyncResult result) {
            SearchShot.ServiceReference1.info retVal = ((SearchShot.ServiceReference1.IService1)(this)).EndGetInfos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInfosCompleted(object state) {
            if ((this.GetInfosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInfosCompleted(this, new GetInfosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInfosAsync(int id_joueur) {
            this.GetInfosAsync(id_joueur, null);
        }
        
        public void GetInfosAsync(int id_joueur, object userState) {
            if ((this.onBeginGetInfosDelegate == null)) {
                this.onBeginGetInfosDelegate = new BeginOperationDelegate(this.OnBeginGetInfos);
            }
            if ((this.onEndGetInfosDelegate == null)) {
                this.onEndGetInfosDelegate = new EndOperationDelegate(this.OnEndGetInfos);
            }
            if ((this.onGetInfosCompletedDelegate == null)) {
                this.onGetInfosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInfosCompleted);
            }
            base.InvokeAsync(this.onBeginGetInfosDelegate, new object[] {
                        id_joueur}, this.onEndGetInfosDelegate, this.onGetInfosCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SearchShot.ServiceReference1.IService1.BeginGetPeopleInfos(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPeopleInfos(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SearchShot.ServiceReference1.personnes SearchShot.ServiceReference1.IService1.EndGetPeopleInfos(System.IAsyncResult result) {
            return base.Channel.EndGetPeopleInfos(result);
        }
        
        private System.IAsyncResult OnBeginGetPeopleInfos(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((SearchShot.ServiceReference1.IService1)(this)).BeginGetPeopleInfos(callback, asyncState);
        }
        
        private object[] OnEndGetPeopleInfos(System.IAsyncResult result) {
            SearchShot.ServiceReference1.personnes retVal = ((SearchShot.ServiceReference1.IService1)(this)).EndGetPeopleInfos(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPeopleInfosCompleted(object state) {
            if ((this.GetPeopleInfosCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPeopleInfosCompleted(this, new GetPeopleInfosCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPeopleInfosAsync() {
            this.GetPeopleInfosAsync(null);
        }
        
        public void GetPeopleInfosAsync(object userState) {
            if ((this.onBeginGetPeopleInfosDelegate == null)) {
                this.onBeginGetPeopleInfosDelegate = new BeginOperationDelegate(this.OnBeginGetPeopleInfos);
            }
            if ((this.onEndGetPeopleInfosDelegate == null)) {
                this.onEndGetPeopleInfosDelegate = new EndOperationDelegate(this.OnEndGetPeopleInfos);
            }
            if ((this.onGetPeopleInfosCompletedDelegate == null)) {
                this.onGetPeopleInfosCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPeopleInfosCompleted);
            }
            base.InvokeAsync(this.onBeginGetPeopleInfosDelegate, null, this.onEndGetPeopleInfosDelegate, this.onGetPeopleInfosCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SearchShot.ServiceReference1.IService1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<SearchShot.ServiceReference1.IService1>, SearchShot.ServiceReference1.IService1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<SearchShot.ServiceReference1.IService1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetData(string value, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = value;
                System.IAsyncResult _result = base.BeginInvoke("GetData", _args, callback, asyncState);
                return _result;
            }
            
            public string EndGetData(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("GetData", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInscription(string password, string login, string mail, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = password;
                _args[1] = login;
                _args[2] = mail;
                System.IAsyncResult _result = base.BeginInvoke("Inscription", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInscription(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Inscription", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAuthentification(string login, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = login;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("Authentification", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndAuthentification(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("Authentification", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetInfos(string nom, string prenom, string login, string ville, int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[5];
                _args[0] = nom;
                _args[1] = prenom;
                _args[2] = login;
                _args[3] = ville;
                _args[4] = id;
                System.IAsyncResult _result = base.BeginInvoke("SetInfos", _args, callback, asyncState);
                return _result;
            }
            
            public string EndSetInfos(System.IAsyncResult result) {
                object[] _args = new object[0];
                string _result = ((string)(base.EndInvoke("SetInfos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetInfos(int id_joueur, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id_joueur;
                System.IAsyncResult _result = base.BeginInvoke("GetInfos", _args, callback, asyncState);
                return _result;
            }
            
            public SearchShot.ServiceReference1.info EndGetInfos(System.IAsyncResult result) {
                object[] _args = new object[0];
                SearchShot.ServiceReference1.info _result = ((SearchShot.ServiceReference1.info)(base.EndInvoke("GetInfos", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetPeopleInfos(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetPeopleInfos", _args, callback, asyncState);
                return _result;
            }
            
            public SearchShot.ServiceReference1.personnes EndGetPeopleInfos(System.IAsyncResult result) {
                object[] _args = new object[0];
                SearchShot.ServiceReference1.personnes _result = ((SearchShot.ServiceReference1.personnes)(base.EndInvoke("GetPeopleInfos", _args, result)));
                return _result;
            }
        }
    }
}
